### ISSUE TITLE
Notensammlung fott

### ISSUE THREAD

**Issue by mirabilos** [musikpirat/mkzae.github.io#1]
https://netzpolitik.org/2013/singen-im-advent-gemeinfreie-advents-und-weihnachtslieder-zum-download/ linkt auf [http://musik.klarmachen-zum-aendern.de/singen-im-advent](http://musik.klarmachen-zum-aendern.de/singen-im-advent) — dat is ävve fott.

Bitte wiederherstellen, danke! ☻

**Comment by mirabilos** [comment]
Ah, ich habe immerhin https://raw.githubusercontent.com/musikpirat/singen-im-advent.github.io/gh-pages/Singen_im_Advent_-_Auflage_3.pdf gefunden. Ist das die letzte Auflage?

Quellen sind nicht verfügbar? Über MusicXML oder zur Not MIDI hätte man die Lieder dann in moderne Notensatzprogramme importieren können.

**Comment by musikpirat** [comment]
Bitte sehr. Freue mich immer, wenn jemand etwas vermisst, dass wir mit viel Herzblutt erstellt haben. :) Via https://web.archive.org/web/20180312145925/http://musik.klarmachen-zum-aendern.de/singen-im-advent wiederhergestellt.

**Comment by mirabilos** [comment]
Danke!
